#!/bin/sh

# track 0.0.1
# track
# A tool to track pupils' progress with iPad maths apps at Danetree.
# Copyright (C) 2013 P. M. Yeeles
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ORIGIN=$PWD;
# TRKDIR='/cygdrive/s/pyeeles/apps/data/track';
TRKDIR=`which danetrack | head -c -11`;
OUTDIR="$HOME/Desktop";

perl $TRKDIR/track-cli.pl;
cd $ORIGIN;